---
title: "Midterm Rules"
author: "Gavin McNicol"
date: "`r Sys.Date()`"
output: 
  tufte::tufte_html:
    css: lab.css
    tufte_variant: "envisioned"
    highlight: pygments
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Midterm Rules

Please read the following instructions in full.

These instructions apply to the in-class midterm which will be held in class **10AM - 12PM on Wednesday, March 27, 2024**.

I will print copies of these instructions and I will post them under **Blackboard \> Weekly Content \> Week 11**.

# Rules during the midterm

## Files, and deadline

Your solutions must be written up in the R Markdown (Rmd) file called `midterm-starter.Rmd`.

This file must include your code and any requested narrative responses.

Your graded submission will be whatever has been **pushed** to your midterm repository.

**Unless** you have requested accommodations, please email to notify me if you need accomodations.\
Commit and push the `midterm-starter.Rmd` as much as you want during the midterm, and again when you are finished.

## Asking for help

If you have technical problems, notify an instructor immediately.

If you are struggling with a question, make an attempt at the answer first.

If you are still getting errors or strange results, ask for help and we will provide some guidance.

You **may not** consult with anyone else about this exam other than the Professor or TA for this course.

Do not ask questions on Slack, or consult with each other, not even for hypothetical questions.

This will be considered cheating.

## Notes, cheatsheets, and help pages

You **can** refer to your Unit 1 - 6 "Cheatsheets", any other hand outs I provided previously (including these instructions), as well as your personal notes, during the in-class exam.

I will bring extra copies of the cheat sheets to the in-class midterm.

You **may not** use online searches but **you may** use R's help pages accessed using `?` for a known package or function or `??` for a general search for a term.

## Exercises and rubric

You will be asked to respond to 8 Exercise questions.

Each Exercise will be worth either 5 or 10 points, for a total of 50 points.

**Respond to every exercise prompt because you will receive a bunch of partial credit for trying**.

You will not be graded on the appearance of your code **but** consider the following elements for each response:

-   Insert or edit code chunks when requested
-   Give your code chunks a unique label
-   Consider whether the chunk should be evaluated (`eval = T` or `eval = F`)
-   Pay attention to typos in functions, pipes, and layering plots
-   When prompted, provide a narrative response alongside your code chunk

## Data and packages

You may only use the `tidyverse` for the midterm (the packages and functions we have covered in class).

Both the pratice midterm and the final midterm will use datasets that are loaded **within packages**.

For example, the practice midterm will use the `earthquakes` dataset from the `{openintro}` package.

Once you load the package with `library(openintro)`, the dataset is availble to you.

## In class logistics

Please try to arrive on time!

I will provide access to your private midterm repos when I see you enter, or join the Zoom.

If you finish early, you are free to leave (*quietly*).

Just make sure you have pushed all your changes to your Github repo!

## Remote participation over Zoom

Please only join remotely if I have given you an exception to be absent.

If you must join remotely, the same rules and logistics apply.

I will not be sharing my screen on Zoom.

I will be wearing an ear-bud so I know you need help if I am not at my computer.

Unmute to notify me you need help, then give me moment to open a breakout room for us to discuss your issue in private.

## Special accoms.

If you have requested special accommodations, I will reach out to you later this week to arrange those.

## Academic Integrity Statement

Before starting the exercises, you will be asked to add your name to agree to the following statement at the top of the `midterm-starter.Rmd` file.

*I, \_\_\_\_\_\_\_\_\_\_\_\_\_, hereby state that I will not communicate with or gain information in any way from my classmates, or copy work from past assignments, during this exam, and that all work is my own.*

## Material covered

The midterm material will mostly cover *Unit 1 - 5*.

Functions and iteration will not be included.

You will not be asked to do anything that was not already covered in previous labs and homework.

To study for the midterm, I encourage you to complete the practice midterm.

They are not identical, but will be very similar.

If you have questions about the midterm:

* Review your notes, past labs and homework and slides.
* Post your question on Slack
* Email an instructor for clarification.

## Laptops to borrow

If you are concerned about your laptop battery or performance during the midterm, please arrive early on the day of the midterm and we can loan you one.
